sonar.projectKey=nandhakumar12_ATS-Resume
sonar.organization=nandhakumar12

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=ATS-Resume
sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
# We are scanning both frontend and backend
sonar.sources=frontend/src,backend/app

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# Exclude coverage test files or specific directories from being analyzed as source code
sonar.exclusions=**/node_modules/**,**/venv/**,**/.venv/**,**/dist/**,**/build/**
